version: "3"
services:
  php:
    tty: true
    stdin_open: true
    user: "$UID"
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./docker/php/php.ini/:/usr/local/etc/php/php.ini
  db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
